name: localstack
services:
  localstack:
    cpu_shares: 90
    command: []
    container_name: localstack
    deploy:
      resources:
        limits:
          memory: 31504M
    environment:
      - DEBUG=0
      - GATEWAY_LISTEN=0.0.0.0:4566
      - LOCALSTACK_AUTH_TOKEN=xxxxxxxxx
      - LOCALSTACK_HOST=[HOST_IP]:4566
      - MAIN_CONTAINER_NAME=localstack
      - PERSISTENCE=1
      - SERVICES=s3,sqs,ses,ec2,lambda,cloudformation,cloudwatch,iam,apigateway,route53,secretsmanager,acm,transcribe,events,kms,sns,sts
    hostname: localstack
    image: localstack/localstack:latest
    labels:
      icon: https://docs.localstack.cloud/images/logo.svg
    ports:
      - target: 4566
        published: "4566"
        protocol: tcp
      - target: 4510
        published: 4510-4559
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/localstack/config
        target: /docker-entrypoint-initaws.d
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    devices: []
    cap_add: []
    network_mode: bridge
    privileged: false
x-casaos:
  author: Wesnetech
  category: Wesnetech
  description:
    en_us: |
      Localstack is a fully functional local AWS cloud stack that enables you to develop and test your cloud and serverless apps offline. It provides an easy-to-use test/mocking framework for developing Cloud applications.
  tagline:
    en_us: The leading platform for local cloud development
  developer: wesscoby
  icon: https://cdn.jsdelivr.net/gh/wesnetech/CasaOS-AppStore@main/Apps/Localstack/icon.svg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/wesnetech/CasaOS-AppStore@main/Apps/Localstack/screenshot-1.png
  thumbnail: https://cdn.jsdelivr.net/gh/wesnetech/CasaOS-AppStore@main/Apps/Localstack/thumbnail.svg
  main: localstack
  is_uncontrolled: false
  port_map: "4566"
  scheme: http
  title:
    custom: Localstack
    en_us: localstack